spring:
  application:
    name: wxshop-order
    datasource:
      url: jdbc:mysql://localhost:3306/order?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver


mybatis:
  config-location: classpath:db/mybatis/config.xml


wxshop:
  orderservice:
    version: 0.0.1
server:
  port: 8081
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.github.kb.order.service